### ISSUE TITLE
`GIT_ALTERNATE_OBJECT_DIRECTORIES` is not honored

### ISSUE THREAD

**Issue by rsrchboy** [git-lfs/gitobj#14]
Alternate object pools are honored -- so long as they're listed in `.git/objects/info/alternates`.  However, `git` also supports listing alternates via `GIT_ALTERNATE_OBJECT_DIRECTORIES` in the environment.
`gitobj` ought to honor `GIT_ALTERNATE_OBJECT_DIRECTORIES`.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I agree we should honor `GIT_ALTERNATE_OBJECT_DIRECTORIES`. I'll see if I can get a fix in soon, although it probably won't make it in for 2.8.0.
