### ISSUE TITLE
Please tag a version

### ISSUE THREAD

**Issue by QuLogic** [git-lfs/gitobj#4]
There's already one for wildmatch; it would be good to have a tagged version of gitobj as well, so that git-lfs depended on tagged versions as much as possible.

**Comment by ttaylorr** [comment]
Hi Elliott. Thanks for your suggestion: I agree it makes sense to do,
and I have pushed a v1.0.0 tag (somewhat arbitrarily) pointing to the
latest HEAD.

We'll make sure to update this as appropriately over time, if things
change in this library.

I believe that we had had existing plans to do this, but were waiting on
some changes that @bk2204 introduced recently before making the plunge.
I dropped the ball on remembering to push the tag once he was done with
his work, but I have done that now.

Thanks again for your suggestion!
